### ISSUE TITLE
Some commands raise an exception

### ISSUE THREAD

**Issue by tylla** [andriykohut/gsem#1]
I tried your code (was a little desperate about managing my extensions without X) but some commands die with an error:
```./gsem enabled
Traceback (most recent call last):
  File "./gsem", line 10, in <module>
    main()
  File "/home/tylla/Projects/gsem/gsem/cli.py", line 105, in main
    l = ["{}@{}".format(e.uuid, e.meta['version']) for e in result]
  File "/home/tylla/Projects/gsem/gsem/cli.py", line 105, in <listcomp>
    l = ["{}@{}".format(e.uuid, e.meta['version']) for e in result]
KeyError: 'version'
```
The same happens for gsem ls.

What went wrong? Did I miss something?

**Comment by andriykohut** [comment]
Hey @tylla! Thanks for reporting, seems like version field is missing from extension metadata, could you please provide me with a list of installed extensions? (`ls ~/.local/share/gnome-shell/extensions/`).

I'm going to investigate, perhaps something changed in `metadata.json` format or you have some borked extension. I should also look into improving the exception handling, as it's not exactly clear what extension caused the error 😬

**Comment by tylla** [comment]
Sure! There are a few... :)

```alternate-tab@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
alt-tab-workspace@kwalo.net
ShellTile@emasab.it
appindicatorsupport@rgcjonas.gmail.com
suspend-button@laserb
auto-move-windows@gnome-shell-extensions.gcampax.github.com
system-monitor@paradoxxx.zero.gmail.com
drive-menu@gnome-shell-extensions.gcampax.github.com
terminal_icon@kirby33
gnomenu@panacier.gmail.com
toggle_nautilus@kirby33
icon-hider@kalnitsky.org
topIcons@adel.gadllah@gmail.com
mediaplayer@patapon.info
tracker-search-provider@sinnix.de
native-window-placement@gnome-shell-extensions.gcampax.github.com
transmission-daemon@patapon.info
notifications-alert-on-user-menu@hackedbellini.gmail.com
unredirect@vaina.lt
openweather-extension@jenslody.de
user-theme@gnome-shell-extensions.gcampax.github.com
pidgin-conversation-integration@kagesenshi.org
weeks-start-on-monday
pidgin-persistent-notification@ikkoku.de
windowoverlay-icons@sustmidown.centrum.cz
remmina-search-provider@alexmurray.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
remove-dropdown-arrows@mpdeimos.com
workspaces-to-dock@passingthru67.gmail.com
```
Btw: I'm using Gnome Shell version 3.14.4 on a Debian Jessie amd64 if that matters.

**Comment by andriykohut** [comment]
@tylla I just pushed a fix to improve error handling, would you mind trying again on latest master? I suspect you have a broken metadata file in one of your extensions, now it shouldn't fail an print more meaningful error message with details about the broken extension.

**Comment by tylla** [comment]
@andriykohut Thanks, it is true, one of my extensions was missing the version entry from its metadata.
Now some new errors have surfaced :), I will post tickets as soon as I can narrow them a little bit.

**Comment by tylla** [comment]
@andriykohut Thanks, it is true, one of my extensions was missing the version entry from its metadata.
Now some new errors have surfaced :), I will post tickets as soon as I can narrow them a little bit.
Thanks again for the fast fix.

**Comment by tylla** [comment]
The new error that I see surfaced when running "gsem info unredirect@vaina.lt" (this is the extensions which has no version info):
```
  File "./bin/gsem", line 10, in <module>
    main()
  File "/home/tylla/Projects/gsem/gsem/cli.py", line 108, in main
    print_info(Extension(args.uuid))
  File "/home/tylla/Projects/gsem/gsem/cli.py", line 66, in print_info
    print("{} - ({})".format(ext.remote_meta['name'], ext.uuid))
  File "/home/tylla/Projects/gsem/gsem/extension.py", line 41, in remote_meta
    'shell_version': '.'.join(str(v) for v in GNOME_SHELL_VERSION),
  File "/home/tylla/Projects/gsem/gsem/utils.py", line 37, in get_json_response
    with urllib.request.urlopen(full_url) as f:
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND
```
Am I right when I assume this is caused by the same problem, the missing version field?
I fixed the missing version field locally by editing metadata.json, but I suppose the online version still lacks this information and this causes the above error when it tries to compare versions.

**Comment by andriykohut** [comment]
@tylla It looks like this extension is removed from https://extensions.gnome.org/, hence it throws `404 NOT FOUND` error. A agree that it shouldn't display the traceback and print something more meaningful instead, like `Requesting extension failed: Not Found`

**Comment by tylla** [comment]
Well, that explains it. :)
It is understandable as the bug this extension works around was fixed some two years ago, but the extensions is still useful for some people  - like me - who do not want / or can't update to a newer gnome version.
As a side effect currently this exception causes that the "gsem outdated" command cannot finish - it exits in the middle.
If you can make some meaningful error handling that would be marvelous.

**Comment by andriykohut** [comment]
Sure thing, I will address this next. Thanks for the feedback! I'll try to make sure that broken/deleted extensions are logged to stderr as warnings and don't break the script completely, still allowing to update the supported ones.

**Comment by andriykohut** [comment]
Fixed in https://github.com/andriykohut/gsem/pull/10
